use crate::errors::CliError;
use crate::output::format::OutputFormat;
use std::collections::HashMap;
use std::fs;

const LOG_PATH: &str = ".autoresearch/experiments.jsonl";
const LESSONS_PATH: &str = ".autoresearch/lessons.md";

pub fn run(json: bool) -> Result<(), CliError> {
    let format = OutputFormat::detect(json);
    generate_lessons(&format)
}

/// Generate lessons from experiment history. Called by `aris learn` and auto-learn in record.
pub fn generate_lessons(format: &OutputFormat) -> Result<(), CliError> {
    let content = fs::read_to_string(LOG_PATH)
        .map_err(|_| CliError::NoExperiments("No experiments".into()))?;

    let experiments: Vec<serde_json::Value> = content
        .lines()
        .filter(|l| !l.trim().is_empty())
        .filter_map(|l| serde_json::from_str(l).ok())
        .collect();

    if experiments.is_empty() {
        return Err(CliError::NoExperiments("No experiments".into()));
    }

    // Gather statistics
    let total = experiments.len();
    let kept_count = experiments.iter().filter(|e| {
        e.get("status").and_then(|s| s.as_str()) == Some("kept")
    }).count();
    let discarded_count = experiments.iter().filter(|e| {
        e.get("status").and_then(|s| s.as_str()) == Some("discarded")
    }).count();
    let baseline_count = experiments.iter().filter(|e| {
        e.get("status").and_then(|s| s.as_str()) == Some("baseline")
    }).count();
    let crash_count = experiments.iter().filter(|e| {
        e.get("status").and_then(|s| s.as_str()) == Some("crash")
    }).count();

    let keep_rate = if total > 0 { (kept_count as f64 / total as f64) * 100.0 } else { 0.0 };

    // Extract summaries by status
    let kept_summaries: Vec<&str> = experiments.iter()
        .filter(|e| e.get("status").and_then(|s| s.as_str()) == Some("kept"))
        .filter_map(|e| e.get("summary").and_then(|s| s.as_str()))
        .collect();

    let discarded_summaries: Vec<&str> = experiments.iter()
        .filter(|e| {
            let s = e.get("status").and_then(|s| s.as_str()).unwrap_or("");
            s == "discarded" || s == "crash" || s == "metric-error"
        })
        .filter_map(|e| e.get("summary").and_then(|s| s.as_str()))
        .collect();

    // Word frequency analysis for strategy grouping
    let effective_strategies = extract_strategies(&kept_summaries);
    let dead_ends = extract_strategies(&discarded_summaries);

    // Metric progression
    let baseline_metric = experiments.iter()
        .find(|e| e.get("status").and_then(|s| s.as_str()) == Some("baseline"))
        .and_then(|e| e.get("metric").and_then(|m| m.as_f64()));

    let best_metric = experiments.iter()
        .filter(|e| {
            let s = e.get("status").and_then(|s| s.as_str()).unwrap_or("");
            s == "kept" || s == "baseline"
        })
        .filter_map(|e| e.get("metric").and_then(|m| m.as_f64()))
        .next_back();

    // Generate lessons.md
    let mut md = String::new();
    md.push_str("# Lessons Learned\n\n");
    md.push_str(&format!("*Auto-generated by `aris learn` at {}*\n\n", chrono::Utc::now().to_rfc3339()));

    // Summary section
    md.push_str("## Summary\n\n");
    md.push_str(&format!("- **Total experiments**: {total}\n"));
    md.push_str(&format!("- **Kept**: {kept_count} ({keep_rate:.0}%)\n"));
    md.push_str(&format!("- **Discarded**: {discarded_count}\n"));
    md.push_str(&format!("- **Baseline**: {baseline_count}\n"));
    if crash_count > 0 {
        md.push_str(&format!("- **Crashes**: {crash_count}\n"));
    }
    if let (Some(base), Some(best)) = (baseline_metric, best_metric) {
        let improvement = ((best - base) / base.abs().max(f64::EPSILON)) * 100.0;
        md.push_str(&format!("- **Metric**: {base:.6} → {best:.6} ({improvement:+.1}%)\n"));
    }
    md.push('\n');

    // Effective Strategies
    md.push_str("## Effective Strategies\n\n");
    if effective_strategies.is_empty() {
        md.push_str("No kept experiments yet — keep iterating.\n\n");
    } else {
        for (theme, summaries) in &effective_strategies {
            md.push_str(&format!("### {theme}\n\n"));
            for s in summaries.iter().take(5) {
                md.push_str(&format!("- {s}\n"));
            }
            md.push('\n');
        }
    }

    // Dead Ends
    md.push_str("## Dead Ends\n\n");
    if dead_ends.is_empty() {
        md.push_str("No failed experiments — unusual, keep experimenting.\n\n");
    } else {
        for (theme, summaries) in &dead_ends {
            md.push_str(&format!("### {theme}\n\n"));
            for s in summaries.iter().take(3) {
                md.push_str(&format!("- {s}\n"));
            }
            md.push('\n');
        }
    }

    // Recommended Next Actions
    md.push_str("## Recommended Next Actions\n\n");
    let recommendations = generate_recommendations(
        total, kept_count, discarded_count, crash_count,
        &effective_strategies, &dead_ends,
    );
    for r in &recommendations {
        md.push_str(&format!("- {r}\n"));
    }
    md.push('\n');

    fs::write(LESSONS_PATH, &md)?;

    match format {
        OutputFormat::Json => {
            let strategies_json: Vec<&str> = effective_strategies
                .iter().flat_map(|(_, v)| v.iter().copied()).collect();
            let dead_ends_json: Vec<&str> = dead_ends
                .iter().flat_map(|(_, v)| v.iter().copied()).collect();

            println!("{}", serde_json::to_string_pretty(&serde_json::json!({
                "status": "success",
                "data": {
                    "statistics": {
                        "total": total,
                        "kept": kept_count,
                        "discarded": discarded_count,
                        "baseline": baseline_count,
                        "crashes": crash_count,
                        "keep_rate": keep_rate,
                    },
                    "strategies": strategies_json,
                    "dead_ends": dead_ends_json,
                },
                "lessons_path": LESSONS_PATH,
            })).unwrap());
        }
        OutputFormat::Table => {
            println!("Lessons generated: {LESSONS_PATH}");
            println!("  {total} experiments analyzed ({kept_count} kept, {discarded_count} discarded, {keep_rate:.0}% keep rate)");
            println!("  {} effective strategies, {} dead ends identified",
                effective_strategies.len(), dead_ends.len());
        }
    }

    Ok(())
}

/// Extract strategy themes from experiment summaries using word frequency.
fn extract_strategies<'a>(summaries: &[&'a str]) -> Vec<(String, Vec<&'a str>)> {
    if summaries.is_empty() {
        return Vec::new();
    }

    // Count significant words (skip common stop words)
    let stop_words = [
        "the", "a", "an", "is", "was", "were", "be", "been", "being",
        "to", "of", "in", "for", "on", "with", "at", "by", "from",
        "and", "or", "but", "not", "no", "this", "that", "it",
        "as", "are", "do", "did", "has", "had", "have",
        "so", "if", "than", "too", "very", "can", "will", "just",
        "more", "also", "some", "any", "each", "which", "when",
        "try", "tried", "used", "using", "use", "added", "add",
        "changed", "change", "set", "new", "old",
    ];

    let mut word_freq: HashMap<String, usize> = HashMap::new();
    for summary in summaries {
        let words: Vec<String> = summary
            .to_lowercase()
            .split(|c: char| !c.is_alphanumeric() && c != '-' && c != '_')
            .filter(|w| w.len() > 2 && !stop_words.contains(w))
            .map(|w| w.to_string())
            .collect();
        // Count unique words per summary
        let unique: std::collections::HashSet<_> = words.into_iter().collect();
        for word in unique {
            *word_freq.entry(word).or_default() += 1;
        }
    }

    // Find themes: words appearing in 2+ summaries
    let mut themes: Vec<(String, usize)> = word_freq
        .into_iter()
        .filter(|(_, count)| *count >= 2)
        .collect();
    themes.sort_by(|a, b| b.1.cmp(&a.1));
    themes.truncate(5);

    // Group summaries by theme
    let mut result: Vec<(String, Vec<&'a str>)> = Vec::new();
    let mut used: std::collections::HashSet<usize> = std::collections::HashSet::new();

    for (theme, _) in &themes {
        let indices: Vec<usize> = summaries
            .iter()
            .enumerate()
            .filter(|(i, s)| {
                !used.contains(i) && s.to_lowercase().contains(theme.as_str())
            })
            .map(|(i, _)| i)
            .collect();
        let matching: Vec<&'a str> = indices
            .iter()
            .map(|&i| {
                used.insert(i);
                summaries[i]
            })
            .collect();
        if !matching.is_empty() {
            // Capitalize theme
            let capitalized = format!(
                "{}{}",
                theme.chars().next().unwrap().to_uppercase(),
                &theme[1..]
            );
            result.push((capitalized, matching));
        }
    }

    // Add ungrouped summaries under "Other"
    let ungrouped: Vec<&'a str> = summaries
        .iter()
        .enumerate()
        .filter(|(i, _)| !used.contains(i))
        .map(|(_, s)| *s)
        .collect();
    if !ungrouped.is_empty() {
        result.push(("Other".to_string(), ungrouped));
    }

    result
}

/// Generate recommendations based on experiment analysis.
fn generate_recommendations(
    total: usize,
    kept: usize,
    discarded: usize,
    crashes: usize,
    strategies: &[(String, Vec<&str>)],
    dead_ends: &[(String, Vec<&str>)],
) -> Vec<String> {
    let mut recs = Vec::new();

    if total < 5 {
        recs.push("Continue experimenting — too few data points for strong recommendations.".into());
        return recs;
    }

    let keep_rate = kept as f64 / total as f64;

    if keep_rate < 0.1 {
        recs.push("Keep rate is very low (<10%). Consider a fundamentally different approach or reviewing program.md for unexplored directions.".into());
    } else if keep_rate > 0.5 {
        recs.push("Keep rate is high (>50%). You're making steady progress — continue refining.".into());
    }

    if crashes > total / 4 {
        recs.push("High crash rate. Fix eval pipeline stability before continuing optimization.".into());
    }

    if !strategies.is_empty() {
        let best_theme = &strategies[0].0;
        recs.push(format!("Most successful strategy theme: \"{best_theme}\". Double down on variations in this direction."));
    }

    if !dead_ends.is_empty() {
        let worst_theme = &dead_ends[0].0;
        recs.push(format!("Most common failure theme: \"{worst_theme}\". Avoid further experiments in this direction."));
    }

    if discarded > 10 && kept < 3 {
        recs.push("Many discards with few keeps. Consider: `aris fork` for parallel exploration, or `aris review` for cross-model analysis.".into());
    }

    if recs.is_empty() {
        recs.push("Keep iterating — mix parameter tuning with structural changes.".into());
    }

    recs
}

/// Check if auto-learn should trigger (called from record). Returns true if lessons should be regenerated.
pub fn should_auto_learn(run_number: usize, config: Option<&toml::Table>) -> bool {
    let interval = config
        .and_then(|c| c.get("learn_interval"))
        .and_then(|v| v.as_integer())
        .map(|i| i as usize)
        .unwrap_or(10);

    if interval == 0 {
        return false;
    }

    run_number > 0 && run_number % interval == 0
}
