use crate::errors::CliError;
use crate::output::format::OutputFormat;
use std::fs;

const LOG_PATH: &str = ".autoresearch/experiments.jsonl";
const LESSONS_PATH: &str = ".autoresearch/lessons.md";

pub fn run(
    format_type: &str,
    limit: Option<usize>,
    since: Option<&str>,
    json: bool,
) -> Result<(), CliError> {
    let format = OutputFormat::detect(json);

    let content = fs::read_to_string(LOG_PATH)
        .map_err(|_| CliError::NoExperiments("No experiments".into()))?;

    let mut experiments: Vec<serde_json::Value> = content
        .lines()
        .filter(|l| !l.trim().is_empty())
        .filter_map(|l| serde_json::from_str(l).ok())
        .collect();

    if experiments.is_empty() {
        return Err(CliError::NoExperiments("No experiments".into()));
    }

    // Apply --since filter
    if let Some(since_date) = since {
        experiments.retain(|e| {
            e.get("timestamp")
                .and_then(|t| t.as_str())
                .map(|t| t >= since_date)
                .unwrap_or(true)
        });
    }

    // Apply --limit
    let limit = limit.unwrap_or(100);
    if experiments.len() > limit {
        experiments = experiments[experiments.len() - limit..].to_vec();
    }

    let total = experiments.len();

    // Gather statistics
    let kept: Vec<&serde_json::Value> = experiments.iter()
        .filter(|e| e.get("status").and_then(|s| s.as_str()) == Some("kept"))
        .collect();
    let discarded_count = experiments.iter()
        .filter(|e| e.get("status").and_then(|s| s.as_str()) == Some("discarded"))
        .count();
    let crash_count = experiments.iter()
        .filter(|e| e.get("status").and_then(|s| s.as_str()) == Some("crash"))
        .count();

    let baseline_metric = experiments.iter()
        .find(|e| e.get("status").and_then(|s| s.as_str()) == Some("baseline"))
        .and_then(|e| e.get("metric").and_then(|m| m.as_f64()));

    let best_metric = experiments.iter()
        .filter(|e| {
            let s = e.get("status").and_then(|s| s.as_str()).unwrap_or("");
            s == "kept" || s == "baseline"
        })
        .filter_map(|e| e.get("metric").and_then(|m| m.as_f64()))
        .next_back();

    // Date range
    let first_ts = experiments.first()
        .and_then(|e| e.get("timestamp").and_then(|t| t.as_str()))
        .unwrap_or("unknown");
    let last_ts = experiments.last()
        .and_then(|e| e.get("timestamp").and_then(|t| t.as_str()))
        .unwrap_or("unknown");

    match format_type {
        "latex-data" => {
            // 10.8: Generate pgfplotstableread data
            let mut tex = String::new();
            tex.push_str("% Auto-generated by aris retrospective --format latex-data\n");
            tex.push_str("\\pgfplotstableread[col sep=comma]{\n");
            tex.push_str("run,metric,status\n");
            for e in &experiments {
                let run = e.get("run").and_then(|r| r.as_u64()).unwrap_or(0);
                let metric = e.get("metric").and_then(|m| m.as_f64())
                    .map(|m| format!("{m:.6}"))
                    .unwrap_or_else(|| "nan".to_string());
                let status = e.get("status").and_then(|s| s.as_str()).unwrap_or("unknown");
                tex.push_str(&format!("{run},{metric},{status}\n"));
            }
            tex.push_str("}\\experiments\n");
            println!("{tex}");
            return Ok(());
        }
        "markdown" | _ => {} // default to markdown
    }

    // Build markdown retrospective
    let mut md = String::new();

    // 10.7: YAML frontmatter for skill consumption
    md.push_str("---\n");
    md.push_str(&"project: aris\n".to_string());
    md.push_str(&format!("date_range: \"{first_ts} to {last_ts}\"\n"));
    md.push_str(&format!("experiment_count: {total}\n"));
    if let Some(best) = best_metric {
        md.push_str(&format!("best_metric: {best:.6}\n"));
    }
    md.push_str("---\n\n");

    md.push_str("# Research Retrospective\n\n");

    // 10.2: Timeline
    md.push_str("## Experiment Timeline\n\n");
    md.push_str("| Run | Status | Metric | Summary |\n");
    md.push_str("|-----|--------|--------|--------|\n");
    for e in &experiments {
        let run = e.get("run").and_then(|r| r.as_u64()).unwrap_or(0);
        let status = e.get("status").and_then(|s| s.as_str()).unwrap_or("-");
        let metric = e.get("metric").and_then(|m| m.as_f64())
            .map(|m| format!("{m:.4}"))
            .unwrap_or_else(|| "-".to_string());
        let summary = e.get("summary").and_then(|s| s.as_str()).unwrap_or("-");
        md.push_str(&format!("| {run} | {status} | {metric} | {summary} |\n"));
    }
    md.push('\n');

    // 10.4: Metrics analysis
    md.push_str("## Metrics Analysis\n\n");
    let metrics: Vec<f64> = experiments.iter()
        .filter_map(|e| e.get("metric").and_then(|m| m.as_f64()))
        .collect();
    if !metrics.is_empty() {
        let min = metrics.iter().copied().fold(f64::INFINITY, f64::min);
        let max = metrics.iter().copied().fold(f64::NEG_INFINITY, f64::max);
        let mean = metrics.iter().sum::<f64>() / metrics.len() as f64;
        let variance = metrics.iter().map(|m| (m - mean).powi(2)).sum::<f64>() / metrics.len() as f64;
        let std_dev = variance.sqrt();

        md.push_str(&format!("- Min: {min:.6}\n"));
        md.push_str(&format!("- Max: {max:.6}\n"));
        md.push_str(&format!("- Mean: {mean:.6}\n"));
        md.push_str(&format!("- Std Dev: {std_dev:.6}\n"));
        if let (Some(base), Some(best)) = (baseline_metric, best_metric) {
            let improvement = ((best - base) / base.abs().max(f64::EPSILON)) * 100.0;
            md.push_str(&format!("- Improvement: {improvement:+.1}% (baseline {base:.6} → best {best:.6})\n"));
        }
    }
    md.push('\n');

    // 10.5: Key decisions (kept experiments)
    md.push_str("## Key Decisions\n\n");
    for e in &kept {
        let run = e.get("run").and_then(|r| r.as_u64()).unwrap_or(0);
        let metric = e.get("metric").and_then(|m| m.as_f64())
            .map(|m| format!("{m:.4}"))
            .unwrap_or_default();
        let summary = e.get("summary").and_then(|s| s.as_str()).unwrap_or("-");
        let delta = e.get("delta").and_then(|d| d.as_f64())
            .map(|d| format!(" (delta: {d:+.4})"))
            .unwrap_or_default();
        md.push_str(&format!("- **#{run}** ({metric}{delta}): {summary}\n"));
    }
    md.push('\n');

    // 10.6: Lessons integration
    if std::path::Path::new(LESSONS_PATH).exists() {
        if let Ok(lessons) = fs::read_to_string(LESSONS_PATH) {
            md.push_str("## Lessons Learned\n\n");
            md.push_str(&lessons);
            md.push('\n');
        }
    }

    // Summary stats
    md.push_str("## Summary Statistics\n\n");
    md.push_str(&format!("- Total: {total}\n"));
    md.push_str(&format!("- Kept: {}\n", kept.len()));
    md.push_str(&format!("- Discarded: {discarded_count}\n"));
    if crash_count > 0 {
        md.push_str(&format!("- Crashes: {crash_count}\n"));
    }
    md.push('\n');

    match format {
        OutputFormat::Json => {
            println!("{}", serde_json::to_string_pretty(&serde_json::json!({
                "status": "success",
                "data": {
                    "total": total,
                    "kept": kept.len(),
                    "discarded": discarded_count,
                    "crashes": crash_count,
                    "baseline_metric": baseline_metric,
                    "best_metric": best_metric,
                    "date_range": [first_ts, last_ts],
                },
                "markdown": md,
            })).unwrap());
        }
        OutputFormat::Table => {
            print!("{md}");
        }
    }

    Ok(())
}
